name: 'Glen Burrows photo & film'
favicon: null
layout_spectrum: 0.09331504441797733
typography_spectrum: 0.5699863727204502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7075039818882942
  lightness: 0.18372122384607792
  saturation: 0.5908849576953799
  rhythmicContrast: 0.6412445672322065
purpose: []
